package br.com.brunoedubems.moeda;
import java.util.ArrayList;
import java.util.List;

public class ListaDeMoeda {

    private static List<Moeda> lista() {
        List<Moeda> lista = new ArrayList<>();
        lista.add(new Moeda("AED", "UAE Dirham", "United Arab Emirates"));
        lista.add(new Moeda("AFN", "Afghan Afghani", "Afghanistan"));
        lista.add(new Moeda("ALL", "Albanian Lek", "Albania"));
        lista.add(new Moeda("AMD", "Armenian Dram", "Armenia"));
        lista.add(new Moeda("ANG", "Netherlands Antillian Guilder", "Netherlands Antilles"));
        lista.add(new Moeda("AOA", "Angolan Kwanza", "Angola"));
        lista.add(new Moeda("ARS", "Argentine Peso", "Argentina"));
        lista.add(new Moeda("AUD", "Australian Dollar", "Australia"));
        lista.add(new Moeda("AWG", "Aruban Florin", "Aruba"));
        lista.add(new Moeda("AZN", "Azerbaijani Manat", "Azerbaijan"));
        lista.add(new Moeda("BAM", "Bosnia and Herzegovina Mark", "Bosnia and Herzegovina"));
        lista.add(new Moeda("BBD", "Barbados Dollar", "Barbados"));
        lista.add(new Moeda("BDT", "Bangladeshi Taka", "Bangladesh"));
        lista.add(new Moeda("BGN", "Bulgarian Lev", "Bulgaria"));
        lista.add(new Moeda("BHD", "Bahraini Dinar", "Bahrain"));
        lista.add(new Moeda("BIF", "Burundian Franc", "Burundi"));
        lista.add(new Moeda("BMD", "Bermudian Dollar", "Bermuda"));
        lista.add(new Moeda("BND", "Brunei Dollar", "Brunei"));
        lista.add(new Moeda("BOB", "Bolivian Boliviano", "Bolivia"));
        lista.add(new Moeda("BRL", "Brazilian Real", "Brazil"));
        lista.add(new Moeda("BSD", "Bahamian Dollar", "Bahamas"));
        lista.add(new Moeda("BTN", "Bhutanese Ngultrum", "Bhutan"));
        lista.add(new Moeda("BWP", "Botswana Pula", "Botswana"));
        lista.add(new Moeda("BYN", "Belarusian Ruble", "Belarus"));
        lista.add(new Moeda("BZD", "Belize Dollar", "Belize"));
        lista.add(new Moeda("CAD", "Canadian Dollar", "Canada"));
        lista.add(new Moeda("CDF", "Congolese Franc", "Democratic Republic of the Congo"));
        lista.add(new Moeda("CHF", "Swiss Franc", "Switzerland"));
        lista.add(new Moeda("CLP", "Chilean Peso", "Chile"));
        lista.add(new Moeda("CNY", "Chinese Renminbi", "China"));
        lista.add(new Moeda("COP", "Colombian Peso", "Colombia"));
        lista.add(new Moeda("CRC", "Costa Rican Colon", "Costa Rica"));
        lista.add(new Moeda("CUP", "Cuban Peso", "Cuba"));
        lista.add(new Moeda("CVE", "Cape Verdean Escudo", "Cape Verde"));
        lista.add(new Moeda("CZK", "Czech Koruna", "Czech Republic"));
        lista.add(new Moeda("DJF", "Djiboutian Franc", "Djibouti"));
        lista.add(new Moeda("DKK", "Danish Krone", "Denmark"));
        lista.add(new Moeda("DOP", "Dominican Peso", "Dominican Republic"));
        lista.add(new Moeda("DZD", "Algerian Dinar", "Algeria"));
        lista.add(new Moeda("EGP", "Egyptian Pound", "Egypt"));
        lista.add(new Moeda("ERN", "Eritrean Nakfa", "Eritrea"));
        lista.add(new Moeda("ETB", "Ethiopian Birr", "Ethiopia"));
        lista.add(new Moeda("EUR", "Euro", "European Union"));
        lista.add(new Moeda("FJD", "Fiji Dollar", "Fiji"));
        lista.add(new Moeda("FKP", "Falkland Islands Pound", "Falkland Islands"));
        lista.add(new Moeda("FOK", "Faroese Króna", "Faroe Islands"));
        lista.add(new Moeda("GBP", "Pound Sterling", "United Kingdom"));
        lista.add(new Moeda("GEL", "Georgian Lari", "Georgia"));
        lista.add(new Moeda("GGP", "Guernsey Pound", "Guernsey"));
        lista.add(new Moeda("GHS", "Ghanaian Cedi", "Ghana"));
        lista.add(new Moeda("GIP", "Gibraltar Pound", "Gibraltar"));
        lista.add(new Moeda("GMD", "Gambian Dalasi", "The Gambia"));
        lista.add(new Moeda("GNF", "Guinean Franc", "Guinea"));
        lista.add(new Moeda("GTQ", "Guatemalan Quetzal", "Guatemala"));
        lista.add(new Moeda("GYD", "Guyanese Dollar", "Guyana"));
        lista.add(new Moeda("HKD", "Hong Kong Dollar", "Hong Kong"));
        lista.add(new Moeda("HNL", "Honduran Lempira", "Honduras"));
        lista.add(new Moeda("HRK", "Croatian Kuna", "Croatia"));
        lista.add(new Moeda("HTG", "Haitian Gourde", "Haiti"));
        lista.add(new Moeda("HUF", "Hungarian Forint", "Hungary"));
        lista.add(new Moeda("IDR", "Indonesian Rupiah", "Indonesia"));
        lista.add(new Moeda("ILS", "Israeli New Shekel", "Israel"));
        lista.add(new Moeda("IMP", "Manx Pound", "Isle of Man"));
        lista.add(new Moeda("INR", "Indian Rupee", "India"));
        lista.add(new Moeda("IQD", "Iraqi Dinar", "Iraq"));
        lista.add(new Moeda("IRR", "Iranian Rial", "Iran"));
        lista.add(new Moeda("ISK", "Icelandic Króna", "Iceland"));
        lista.add(new Moeda("JEP", "Jersey Pound", "Jersey"));
        lista.add(new Moeda("JMD", "Jamaican Dollar", "Jamaica"));
        lista.add(new Moeda("JOD", "Jordanian Dinar", "Jordan"));
        lista.add(new Moeda("JPY", "Japanese Yen", "Japan"));
        lista.add(new Moeda("KES", "Kenyan Shilling", "Kenya"));
        lista.add(new Moeda("KGS", "Kyrgyzstani Som", "Kyrgyzstan"));
        lista.add(new Moeda("KHR", "Cambodian Riel", "Cambodia"));
        lista.add(new Moeda("KID", "Kiribati Dollar", "Kiribati"));
        lista.add(new Moeda("KMF", "Comorian Franc", "Comoros"));
        lista.add(new Moeda("KRW", "South Korean Won", "South Korea"));
        lista.add(new Moeda("KWD", "Kuwaiti Dinar", "Kuwait"));
        lista.add(new Moeda("KYD", "Cayman Islands Dollar", "Cayman Islands"));
        lista.add(new Moeda("KZT", "Kazakhstani Tenge", "Kazakhstan"));
        lista.add(new Moeda("LAK", "Lao Kip", "Laos"));
        lista.add(new Moeda("LBP", "Lebanese Pound", "Lebanon"));
        lista.add(new Moeda("LKR", "Sri Lanka Rupee", "Sri Lanka"));
        lista.add(new Moeda("LRD", "Liberian Dollar", "Liberia"));
        lista.add(new Moeda("LSL", "Lesotho Loti", "Lesotho"));
        lista.add(new Moeda("LYD", "Libyan Dinar", "Libya"));
        lista.add(new Moeda("MAD", "Moroccan Dirham", "Morocco"));
        lista.add(new Moeda("MDL", "Moldovan Leu", "Moldova"));
        lista.add(new Moeda("MGA", "Malagasy Ariary", "Madagascar"));
        lista.add(new Moeda("MKD", "Macedonian Denar", "North Macedonia"));
        lista.add(new Moeda("MMK", "Burmese Kyat", "Myanmar"));
        lista.add(new Moeda("MNT", "Mongolian Tögrög", "Mongolia"));
        lista.add(new Moeda("MOP", "Macanese Pataca", "Macau"));
        lista.add(new Moeda("MRU", "Mauritanian Ouguiya", "Mauritania"));
        lista.add(new Moeda("MUR", "Mauritian Rupee", "Mauritius"));
        lista.add(new Moeda("MVR", "Maldivian Rufiyaa", "Maldives"));
        lista.add(new Moeda("MWK", "Malawian Kwacha", "Malawi"));
        lista.add(new Moeda("MXN", "Mexican Peso", "Mexico"));
        lista.add(new Moeda("MYR", "Malaysian Ringgit", "Malaysia"));
        lista.add(new Moeda("MZN", "Mozambican Metical", "Mozambique"));
        lista.add(new Moeda("NAD", "Namibian Dollar", "Namibia"));
        lista.add(new Moeda("NGN", "Nigerian Naira", "Nigeria"));
        lista.add(new Moeda("NIO", "Nicaraguan Córdoba", "Nicaragua"));
        lista.add(new Moeda("NOK", "Norwegian Krone", "Norway"));
        lista.add(new Moeda("NPR", "Nepalese Rupee", "Nepal"));
        lista.add(new Moeda("NZD", "New Zealand Dollar", "New Zealand"));
        lista.add(new Moeda("OMR", "Omani Rial", "Oman"));
        lista.add(new Moeda("PAB", "Panamanian Balboa", "Panama"));
        lista.add(new Moeda("PEN", "Peruvian Sol", "Peru"));
        lista.add(new Moeda("PGK", "Papua New Guinean Kina", "Papua New Guinea"));
        lista.add(new Moeda("PHP", "Philippine Peso", "Philippines"));
        lista.add(new Moeda("PKR", "Pakistani Rupee", "Pakistan"));
        lista.add(new Moeda("PLN", "Polish Złoty", "Poland"));
        lista.add(new Moeda("PYG", "Paraguayan Guaraní", "Paraguay"));
        lista.add(new Moeda("QAR", "Qatari Riyal", "Qatar"));
        lista.add(new Moeda("RON", "Romanian Leu", "Romania"));
        lista.add(new Moeda("RSD", "Serbian Dinar", "Serbia"));
        lista.add(new Moeda("RUB", "Russian Ruble", "Russia"));
        lista.add(new Moeda("RWF", "Rwandan Franc", "Rwanda"));
        lista.add(new Moeda("SAR", "Saudi Riyal", "Saudi Arabia"));
        lista.add(new Moeda("SBD", "Solomon Islands Dollar", "Solomon Islands"));
        lista.add(new Moeda("SCR", "Seychellois Rupee", "Seychelles"));
        lista.add(new Moeda("SDG", "Sudanese Pound", "Sudan"));
        lista.add(new Moeda("SEK", "Swedish Krona", "Sweden"));
        lista.add(new Moeda("SGD", "Singapore Dollar", "Singapore"));
        lista.add(new Moeda("SHP", "Saint Helena Pound", "Saint Helena"));
        lista.add(new Moeda("SLE", "Sierra Leonean Leone", "Sierra Leone"));
        lista.add(new Moeda("SOS", "Somali Shilling", "Somalia"));
        lista.add(new Moeda("SRD", "Surinamese Dollar", "Suriname"));
        lista.add(new Moeda("SSP", "South Sudanese Pound", "South Sudan"));
        lista.add(new Moeda("STN", "São Tomé and Príncipe Dobra", "São Tomé and Príncipe"));
        lista.add(new Moeda("SYP", "Syrian Pound", "Syria"));
        lista.add(new Moeda("SZL", "Eswatini Lilangeni", "Eswatini"));
        lista.add(new Moeda("THB", "Thai Baht", "Thailand"));
        lista.add(new Moeda("TJS", "Tajikistani Somoni", "Tajikistan"));
        lista.add(new Moeda("TMT", "Turkmenistan Manat", "Turkmenistan"));
        lista.add(new Moeda("TND", "Tunisian Dinar", "Tunisia"));
        lista.add(new Moeda("TOP", "Tongan Paʻanga", "Tonga"));
        lista.add(new Moeda("TRY", "Turkish Lira", "Turkey"));
        lista.add(new Moeda("TTD", "Trinidad and Tobago Dollar", "Trinidad and Tobago"));
        lista.add(new Moeda("TVD", "Tuvaluan Dollar", "Tuvalu"));
        lista.add(new Moeda("TWD", "New Taiwan Dollar", "Taiwan"));
        lista.add(new Moeda("TZS", "Tanzanian Shilling", "Tanzania"));
        lista.add(new Moeda("UAH", "Ukrainian Hryvnia", "Ukraine"));
        lista.add(new Moeda("UGX", "Ugandan Shilling", "Uganda"));
        lista.add(new Moeda("USD", "United States Dollar", "United States"));
        lista.add(new Moeda("UYU", "Uruguayan Peso", "Uruguay"));
        lista.add(new Moeda("UZS", "Uzbekistani So'm", "Uzbekistan"));
        lista.add(new Moeda("VES", "Venezuelan Bolívar Soberano", "Venezuela"));
        lista.add(new Moeda("VND", "Vietnamese Đồng", "Vietnam"));
        lista.add(new Moeda("VUV", "Vanuatu Vatu", "Vanuatu"));
        lista.add(new Moeda("WST", "Samoan Tālā", "Samoa"));
        lista.add(new Moeda("XAF", "Central African CFA Franc", "CEMAC"));
        lista.add(new Moeda("XCD", "East Caribbean Dollar", "Organisation of Eastern Caribbean States"));
        lista.add(new Moeda("XDR", "Special Drawing Rights", "International Monetary Fund"));
        lista.add(new Moeda("XOF", "West African CFA franc", "CFA"));
        lista.add(new Moeda("XPF", "CFP Franc", "Collectivités d'Outre-Mer"));
        lista.add(new Moeda("YER", "Yemeni Rial", "Yemen"));
        lista.add(new Moeda("ZAR", "South African Rand", "South Africa"));
        lista.add(new Moeda("ZMW", "Zambian Kwacha", "Zambia"));
        lista.add(new Moeda("ZWL", "Zimbabwean Dollar", "Zimbabwe"));

        return lista;
    }

    public static void exibirTodas() {
        List<Moeda> moedas = lista();
        for (Moeda moeda : moedas) {
            System.out.println("Codigo:" + moeda.getCode() + " - Moeda" + moeda.getName() + " (" + moeda.getCountry() + ")");
        }
    }


}
